variables:
  Azure.Connection:      'Azure Subscription'
  Azure.ResourceGroup:   'demo-e2e-app-test'
  Azure.WebAppName:      'e2e-app-test'
  Azure.SlotName:        'staging'
  EnvironmentName:       'e2e-aspnetcore6-test'
  SomeSetting:           'Value for TEST env (defined in YAML)'
