# File:           Jobs/ensure-tests.yml
# Template type:  Job Template
# Description:    Add this job to your build stage to ensure tests were run.
# Author:         Neno Loje
# Created:        July 27, 2019
# Prerequisites:  Add a "dependsOn" attribute, so this job runs after your build job.
# Ext. required:  https://marketplace.visualstudio.com/items?itemName=jessehouwing.vsts-ensure-tests-tasks

parameters:
- name: minNumOfExpectedTests
  type: number
  default: 1
- name: dependsOn
  type: string

jobs:
- job: EnsureTests
  displayName: 'Check Test Results'
  dependsOn: ${{ parameters.dependsOn }}
  pool: server
  steps:
  - task: Ensure tests have executed.@0
    displayName: 'Check # total tests run'
    inputs:
      minNumOfExpectedTests: ${{ parameters.minNumOfExpectedTests }}
