parameters:
- name: stageName # specify stage in PascalCase like this: "Test", "Prod"
  type: string

stages:  
- stage: ${{ upper(parameters.stageName) }}

  variables:
  - template: Config/Stage-${{ parameters.stageName }}.yml

  jobs:
  - template: Job-DeployInfrastructure.yml
    parameters:
      jobName: DeployInfra
      azureSubscription: ${{ variables['Azure.Connection'] }}

  - template: Job-DeployWebApp.yml
    parameters:
      jobName: DeployWebApp
      dependsOn: DeployInfra
      environmentName: ${{ variables.EnvironmentName }}
      azureSubscription: ${{ variables['Azure.Connection'] }}

  - template: Job-RunUITests.yml
    parameters:
      jobName: FunctionalTests
      dependsOn: DeployWebApp
