# File        : Build.yml
# Description : This is the main build pipeline file for this project.

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - topic/*
  paths:
    exclude:
    - .azuredevops/*
    - Docs/*
    - Pipelines/*.yml
    - Pipelines/Templates/*.yml
    - azurepipelines-coverage.yml
    - README.md

variables:
  buildConfiguration: 'Release'

jobs:
- template: Build/Job-BuildWebApp.yml
  parameters:
    jobName: BuildWebApp
    buildConfiguration: $(buildConfiguration)

- template: Build/Job-BuildInfrastructure.yml
  parameters:
    jobName: BuildInfra


- template: Build/Job-BuildSQLDB.yml
  parameters:
    jobName: BuildDB
    buildConfiguration: $(buildConfiguration)
    solutionFile:       'Application/aspnet-core-sample.sln'
    projectName:        'aspnet-core-sample.Database'

- template: Templates/Jobs/Ensure-Tests.yml
  parameters:
    dependsOn: BuildWebApp
    minNumOfExpectedTests: 1
