# File        : Build.yml
# Description : This is the main build pipeline file for this project.

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - topic/*
  paths:
    exclude:
    - .azuredevops/*
    - Docs/*
    - Pipelines/*.yml
    - Pipelines/Templates/*.yml
    - azurepipelines-coverage.yml
    - README.md

variables:
  buildConfiguration: 'Release'

jobs:
- template: Build-WebApp.yml
  parameters:
    jobName: BuildWebApp
    buildConfiguration: $(buildConfiguration)

- template: Build-Infrastructure.yml
  parameters:
    jobName: BuildInfra
