# File        : Build.yml
# Description : This is the main build pipeline file for this project.
# Author      : Neno Loje

trigger:
  batch: true
  branches:
    include:
    - main
    - feature/*
    - topic/*
  paths:
    exclude:
    - .azuredevops/*
    - Docs/*
    - Pipelines/*
    - README.md

variables:
  buildConfiguration: 'Release'

jobs:
- template: Build-WebApp.yml
  parameters:
    jobName: BuildWebApp
    buildConfiguration: $(buildConfiguration)
