# File        : Deploy.yml
# Description : This is our main deployment pipeline.

trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: e2e-aspnetcore6.Build
    trigger:
      branches:
        include:
        - main

variables:
- template: Config/Pipeline-Global.yml

stages:
- template: Deploy-Stage-Template.yml
  parameters:
    stageName: Test

- template: Deploy-Stage-Template.yml
  parameters:
    stageName: Prod
