# File: Deploy-Infrastructure.yml

# Description : This job template describes a deployment to an Azure resource group.
# Author      : Neno Loje
# Created     : February 22, 2020

parameters:
- name: jobName
- name: azureConnection

jobs:
- job: ${{ parameters.jobName }}
  variables:
  - template: Config/Stage-Test.yml
  steps:
  - checkout: none

  - template: Templates/Steps/Print-DebugInfo.yml

  # By default, files are downloaded to $(Pipeline.Workspace)/{pipeline}/{artifact}
  - download: CI
    displayName: 'Download artifact: ArmTemplate'
    artifact: ArmTemplate

  - template: Templates/Steps/AzureCLI/Create-ResourceGroup.yml
    parameters:
      azureSubscription: ${{ parameters.azureConnection }}
      name: $(Azure.ResourceGroup)
      location: $(Azure.Region)

# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
  - task: AzureResourceGroupDeployment@2
    displayName: 'Deploy Azure resources (complete mode)'
    inputs:
      azureSubscription:  ${{ parameters.azureConnection }}
      action:             Create Or Update Resource Group
      resourceGroupName:  $(Azure.ResourceGroup)
      location:           $(Azure.Region)
      templateLocation:   Linked artifact
      csmFile:            $(Pipeline.Workspace)/CI/ArmTemplate/azure-deploy.json
      overrideParameters: >-
        appName=${{ variables['Azure.WebAppName'] }}
      #  -webAppName "$(Azure.WebAppName)"
      #  -hostingPlanName "$(Azure.WebAppName)-plan"
      #  -appInsightsLocation "$(Azure.Region)"
      #  -sku "$(Azure.WebAppPlanSKU)"
      #  -slotName "$(Azure.SlotName)"
      #  -databaseServerName "$(SQLAzure.ServerName)"
      #  -databaseName "$(SQLAzure.DatabaseName)"
      #  -databaseUsername "$(SQLAzure.Username)"
      #  -databasePassword "$(SQLAzure.Password)"
      #  -keyVaultName "$(Azure.KeyVaultName)"
      #  -keyVaultObjectId "$(Azure.KeyVaultOwner)"
      deploymentMode:     Complete
