# File        : Deploy.yml
# Description : This is our main deployment pipeline.

trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: e2e-aspnetcore6.Build
    trigger:
      branches:
        include:
        - main

stages:
- stage: TEST
  jobs:
  - template: Deploy-Infrastructure.yml
    parameters:
      jobName: DeployInfra
      azureConnection: 'Azure Subscription'
