# File: Deploy-Infrastructure.yml

# Description : This job template describes a deployment to an Azure resource group.
# Author      : Neno Loje
# Created     : February 22, 2020

parameters:
- name: jobName
  type: string
- name: azureConnection
  type: string

jobs:
- job: ${{ parameters.jobName }}

  pool:
    name: default

  variables:
  - template: Config/Stage-Test.yml
  - name: armTemplateFile
    value: '$(Pipeline.Workspace)/CI/ArmTemplate/azuredeploy.json'

  steps:
  - checkout: none

  - template: Templates/Steps/Print-DebugInfo.yml

  # By default, files are downloaded to $(Pipeline.Workspace)/{pipeline}/{artifact}
  - download: CI
    displayName: 'Download artifact: ArmTemplate'
    artifact: ArmTemplate

  - template: Templates/Steps/AzureCLI/Create-ResourceGroup.yml
    parameters:
      azureSubscription: ${{ parameters.azureConnection }}
      name: $(Azure.ResourceGroup)
      location: $(Azure.Region)

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope:                'Resource Group'
      azureResourceManagerConnection: '${{ parameters.azureConnection }}'
      #subscriptionId:                 '9b4b958c-bd31-4c60-a834-c4bb38488748'
      action:                         'Create Or Update Resource Group'
      resourceGroupName:              '$(Azure.ResourceGroup)'
      location:                       '$(Azure.Region)'
      templateLocation:               'Linked artifact'
      csmFile:                        '$(armTemplateFile)'
      deploymentMode:                 'Complete'
      overrideParameters: >-
        -appName "${{ variables['Azure.WebAppName'] }}"

# # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
#   - task: AzureResourceGroupDeployment@2
#     displayName: 'Deploy Azure resources (complete mode)'
#     inputs:
#       azureSubscription:  ${{ parameters.azureConnection }}
#       action:             Create Or Update Resource Group
#       resourceGroupName:  $(Azure.ResourceGroup)
#       location:           $(Azure.Region)
#       templateLocation:   Linked artifact
#       csmFile:            $(Pipeline.Workspace)/CI/ArmTemplate/azuredeploy.json
#       overrideParameters: >-
#         -appName ${{ variables['Azure.WebAppName'] }}
#       #  -webAppName "$(Azure.WebAppName)"
#       #  -hostingPlanName "$(Azure.WebAppName)-plan"
#       #  -appInsightsLocation "$(Azure.Region)"
#       #  -sku "$(Azure.WebAppPlanSKU)"
#       #  -slotName "$(Azure.SlotName)"
#       #  -databaseServerName "$(SQLAzure.ServerName)"
#       #  -databaseName "$(SQLAzure.DatabaseName)"
#       #  -databaseUsername "$(SQLAzure.Username)"
#       #  -databasePassword "$(SQLAzure.Password)"
#       #  -keyVaultName "$(Azure.KeyVaultName)"
#       #  -keyVaultObjectId "$(Azure.KeyVaultOwner)"
#       deploymentMode:     Complete
