# File        : Deploy.yml
# Description : This is our main deployment pipeline.

trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: e2e-aspnetcore6.Build
    trigger:
      branches:
        include:
        - main

variables:
- template: Config/Pipeline-Global.yml

stages:
#--------------------------------------------------------------------------------
- stage: TEST

  variables:
  - template: Config/Stage-Test.yml

  jobs:
  - template: Deploy-Infrastructure.yml
    parameters:
      jobName: DeployInfra
      azureConnection: 'Azure Subscription'

  - template: Deploy-WebApp.yml
    parameters:
      jobName: DeployWebApp
      dependsOn: DeployInfra
      environmentName: $(EnvironmentName)
      azureConnection: 'Azure Subscription'
