# File        : PR-SecretScanning.yml
# Description : Scans the source code for secrets.
# Author      : Neno Loje
# Requires    : Gitleaks extension: https://marketplace.visualstudio.com/items?itemName=Foxholenl.Gitleaks

trigger: none

parameters:
- name: verbose
  displayName: 'Print verbose output'
  type: boolean
  default: false

steps:
- task: Gitleaks@1
  displayName: 'Run Gitleaks tool'
  inputs:
    scanfolder: '$(Build.SourcesDirectory)'
    configfile: 'default'
    prevalidationbuild: true
    taskfail: true
    reportformat: 'sarif'
    uploadresults: false # True did not work for me.
    version: 'latest'
    taskfailonexecutionerror: true
    verbose: ${{ parameters.verbose }}

- publish: $(Agent.TempDirectory)
  displayName: 'Publish CodeAnalysisLogs'
  artifact: 'CodeAnalysisLogs'
