# File        : PR-SecretScanning.yml
# Description : Scans the source code for secrets.
# Author      : Neno Loje

trigger: none

parameters:
- name: verbose
  displayName: 'Print verbose output'
  type: boolean
  default: false

steps:
- task: Gitleaks@1
  displayName: 'Run Gitleaks tool'
  inputs:
    scanfolder: '$(Build.SourcesDirectory)'
    configfile: 'default'
    prevalidationbuild: true
    taskfail: true
    reportformat: 'sarif'
    uploadresults: true
    version: 'latest'
    taskfailonexecutionerror: true
    verbose: ${{ parameters.verbose }}
