trigger: none

parameters:
- name: agentType
  displayName: 'Choose agent to run pipeline'
  default: 'on-prem'
  values:
  - 'cloud'
  - 'on-prem'

jobs:
- template: Utils/Job-AzDevOpsCLI.yml
  parameters:
    agentType: ${{ parameters.agentType }}
