trigger: none

parameters:
- name: agentPool
  displayName: 'Enter agent pool to run'
  type: object
  default:
    name: Default

pool:
  ${{ parameters.agentPool }}

steps:
- powershell: | 
    az --version
    az extension add --name azure-devops
    az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
    ./Pipelines/Utils/ConfigureBranchPolicies.ps1
  displayName: 'Run ConfigureBranchPolicies.ps1'
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
